trigger:
- main

pool:
  name: Default

variables:
  # Using variables makes it easier to change later
  imageRepository: 'santhoshsk3722/devops-demo' 
  dockerfilePath: 'app/Dockerfile'
  tag: '$(Build.BuildId)'

stages:
- stage: Build
  displayName: Build Spring Boot App
  jobs:
  - job: MavenBuild
    steps:
    - task: Maven@4
      inputs:
        mavenPomFile: 'app/pom.xml'
        goals: 'clean package'
        publishJUnitResults: false
        javaHomeOption: 'Path'
        jdkDirectory: 'C:\Program Files\Eclipse Adoptium\jdk-17.0.18.8-hotspot' # Ensure this matches your local path
        jdkArchitectureOption: 'x64'

- stage: Docker
  displayName: Build Docker Image
  dependsOn: Build
  condition: succeeded() # Only run if Build stage passes
  jobs:
  - job: DockerBuild
    steps:
    - task: Docker@2
      displayName: Build and Push
      inputs:
        containerRegistry: 'dockerhub' # This name must match Project Settings exactly
        repository: 'santhoshsk3722/devops-project'
        command: 'buildAndPush'
        Dockerfile: '**/Dockerfile'
        tags: |
          $(tag)
          latest