trigger:
- main

pool:
  name: Default

variables:
  # Using variables makes it easier to change later
  imageRepository: 'santhoshsk3722/devops-demo' 
  dockerfilePath: 'app/Dockerfile'
  tag: '$(Build.BuildId)'

stages:
- stage: Build
  displayName: Build Spring Boot App
  jobs:
  - job: MavenBuild
    steps:
    - task: Maven@3
      inputs:
        mavenPomFile: 'app/pom.xml'
        goals: 'clean package'
        publishJUnitResults: false
        javaHomeOption: 'Path'
        jdkDirectory: 'C:\Program Files\Java\jdk-17' # Ensure this matches your local path
        jdkArchitectureOption: 'x64'

- stage: Docker
  displayName: Build Docker Image
  dependsOn: Build
  condition: succeeded() # Only run if Build stage passes
  jobs:
  - job: DockerBuild
    steps:
    - task: Docker@2
      displayName: Build and Push to Docker Hub
      inputs:
        containerRegistry: 'dockerhub'
        repository: $(imageRepository)
        command: 'buildAndPush'
        Dockerfile: $(dockerfilePath)
        tags: |
          $(tag)
          latest